site_name: SkeletonWatershed

copyright: Copyright (c) 2024 Norbert Toth

theme:
    name: readthedocs
    highlightjs: true

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

nav:
  - SkeletonWatershed: first_page.md
  - Example:
    Example: Example.ipynb
  - Licence:
    Licence: licence.md
